### PR TITLE
Cairo: Add ERC1155

### PR DESCRIPTION
**Pull request by ericglau**
- Use OpenZeppelin Contracts for Cairo v0.11.0.
- Add ERC1155.
- Remove redundant not paused assertions for camel case functions.
- Fix use of ERC20 mixin.
- Sort imports alphabetically.

### CODE REVIEW

**Comment by ericglau** [comment]
@SocketSecurity ignore npm/svelte-preprocess@5.1.3

**Review by ericnordelo — APPROVED** [review]
LGTM!

**Review by andrew-fleming — COMMENTED** [review]
Changes look good! One small thing: I know it's by design to import the components first, but it appears a little unorganized when, for instance, selecting `Roles` and `Upgradeable`. Here's the ouput:

```
    use openzeppelin::token::erc1155::ERC1155Component;
    use openzeppelin::introspection::src5::SRC5Component
    use openzeppelin::access::accesscontrol::AccessControlComponent
    use openzeppelin::upgrades::UpgradeableComponent
    use openzeppelin::access::accesscontrol::DEFAULT_ADMIN_ROLE
    use openzeppelin::upgrades::interface::IUpgradeable;
```

The cairo formatter alphabetizes the imports on our end. IMO it'd make sense to follow the formatter. It should also help simplify [getCategorizedImports](https://github.com/ericglau/contracts-wizard/blob/cairo1155/packages/core-cairo/src/print.ts#L59-L71) in the wizard 🤞 what do you think?

**Review by andrew-fleming — APPROVED** [review]
LGTM!

**Pull request merged**
